#!/bin/bash
java replace input1.txt output.txt 123 man
if cmp -s output.txt result1.txt ; then
 echo test 1 passed
else 
 echo test 1 failed
fi 

java replace input2.txt output.txt job slave
if cmp -s output.txt result2.txt ; then
 echo test 2 passed
else 
 Echo test 2 failed
fi 

java replace input3.txt output.txt 1231234 clever
if cmp -s output.txt result3.txt ; then
 echo test 3 passed
else 
 Echo test 3 failed
fi

java replace none.txt output.txt 1231234 clever > output.txt
if cmp -s output.txt result4.txt ; then
 echo test 4 passed
else
 Echo test 4 failed
fi

java replace input3.txt none.txt 1231234 clever > output.txt
if cmp -s output.txt result5.txt ; then
 echo test 5 passed
else
 Echo test 5 failed
fi

java replace input3.txt none.txt > output.txt
if cmp -s output.txt result6.txt ; then
 echo test 6 passed
else
 Echo test 6 failed
fi