#!/bin/bash
java Dec2bin > result.txt
if cmp -s result.txt result1.txt ; then
 echo test 1 passed
else 
 echo test 1 exit code $?
fi 

java Dec2bin -1 > result.txt
if cmp -s result.txt result2.txt ; then
 echo test 2 passed
else 
 echo test 2 exit code $?
fi 

java Dec2bin 23 > result.txt
if cmp -s result.txt result3.txt ; then
 echo test 3 passed
else 
 echo test 3 exit code $?
fi 

java Dec2bin 4294967295 > result.txt
if cmp -s result.txt result4.txt ; then
 echo test 4 passed
else 
 echo test 4 exit code $?
fi

java Dec2bin 0 > result.txt
if cmp -s result.txt result5.txt ; then
 echo test 5 passed
else
 echo test 5 exit code $?
fi