#!/bin/bash
java dec2bin > result.txt
if cmp -s result.txt result1.txt ; then
 echo test 1 passed
else 
 echo test 1 failed
fi 

java dec2bin -1 > result.txt
if cmp -s result.txt result2.txt ; then
 echo test 2 passed
else 
 Echo test 2 failed
fi 

java dec2bin 23 > result.txt
if cmp -s result.txt result3.txt ; then
 echo test 3 passed
else 
 Echo test 3 failed
fi 

java dec2bin 4294967295 > result.txt
if cmp -s result.txt result4.txt ; then
 echo test 4 passed
else 
 echo test 4 failed
fi