#!/bin/bash
java Invert > result.txt
if cmp -s result.txt result1.txt ; then
 echo test 1 passed
else 
 echo test 1 exit code $?
fi 

java Invert none.txt > result.txt
if cmp -s result.txt result2.txt ; then
 echo test 2 passed
else
 echo test 2 exit code $?
fi

java Invert input3.txt > result.txt
if cmp -s result.txt result3.txt ; then
 echo test 3 passed
else
 echo test 3 exit code $?
fi

java Invert input4.txt > result.txt
if cmp -s result.txt result4.txt ; then
 echo test 4 passed
else
 echo test 4 exit code $?
fi

java Invert input5.txt > result.txt
if cmp -s result.txt result5.txt ; then
 echo test 5 passed
else
 echo test 5 exit code $?
fi

java Invert input6.txt > result.txt
if cmp -s result.txt result6.txt ; then
 echo test 6 passed
else
 echo test 6 exit code $?
fi

java Invert input7.txt > result.txt
if cmp -s result.txt result7.txt ; then
 echo test 7 passed
else
 echo test 7 exit code $?
fi